package ekh.challenge.barksky.overview

import androidx.lifecycle.ViewModelProviders
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.lifecycle.ViewModelProvider

import ekh.challenge.barksky.databinding.OverviewFragmentBinding


class OverviewFragment : Fragment() {
    private val viewModel: OverviewViewModel by lazy {ViewModelProvider(this).get(OverviewViewModel::class.java)}

    companion object {
        fun newInstance() = OverviewFragment()
//        TODO: Generated by androidStudio, still needed?
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        val binding = OverviewFragmentBinding.inflate(inflater)
        binding.setLifecycleOwner(this)
        binding.viewModel = viewModel
        return binding.root
    }
}
